name: clean_architecture_posts_app
description: Posts App with clean architecture


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5

  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Functional programming things
  dartz: ^0.10.1
  # Service locator
  get_it: ^7.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  mocktail:  
  bloc_test: 
  build_runner: 
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/trips_mock.json

 
  uses-material-design: true

